name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar dependências
        run: |
          npm install

      - name: Instalar Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Criar configuração Capacitor
        run: |
          npx cap init Biblioteca com.exemplo.biblioteca --web-dir=dist

      - name: Adicionar Android
        run: |
          npx cap add android

      - name: Sincronizar Android
        run: |
          npx cap sync android

      - name: Gerar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: Biblioteca-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
